# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-21 09:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, verbose_name='label')),
                ('label_en', models.CharField(max_length=100, null=True, verbose_name='label')),
                ('label_ar', models.CharField(max_length=100, null=True, verbose_name='label')),
                ('file', models.FileField(upload_to='', verbose_name='file')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
    ]
