# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-21 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='public',
            field=models.BooleanField(default=True, verbose_name='public'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(upload_to='attachments/', verbose_name='file'),
        ),
    ]
