# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-12 13:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0002_auto_20200221_1231'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attachment',
            options={'verbose_name': 'attachment', 'verbose_name_plural': 'attachments'},
        ),
    ]
