# Generated by Django 3.0.6 on 2020-07-02 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='text_ar',
            field=models.TextField(help_text='Content of the static page, in Markdown', null=True, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='page',
            name='text_en',
            field=models.TextField(help_text='Content of the static page, in Markdown', null=True, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='page',
            name='title_ar',
            field=models.CharField(max_length=100, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='page',
            name='title_en',
            field=models.CharField(max_length=100, null=True, verbose_name='title'),
        ),
    ]
