# Generated by Django 3.0.6 on 2020-07-24 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20200703_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Last modified'),
        ),
    ]
