# Generated by Django 3.0.7 on 2020-09-21 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Our notes'),
        ),
    ]
