# Generated by Django 3.0.7 on 2020-09-21 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20200922_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='submitter',
            field=models.EmailField(max_length=254, null=True, verbose_name='submitted by'),
        ),
    ]
