# Generated by Django 3.0.7 on 2020-11-11 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_report_submitter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='submitter',
            field=models.CharField(max_length=100, null=True, verbose_name='submitted by'),
        ),
    ]
