# Generated by Django 3.0.7 on 2021-08-11 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_auto_20201111_0356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='country',
            field=models.CharField(choices=[('lebanon', 'Lebanon'), ('jordan', 'Jordan'), ('tunisia', 'Tunisia'), ('other', 'Other')], max_length=10, verbose_name='country'),
        ),
    ]
