# Generated by Django 3.0.6 on 2020-06-01 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(blank=True, verbose_name='summary')),
                ('summary_ar', models.TextField(blank=True, null=True, verbose_name='summary')),
                ('summary_en', models.TextField(blank=True, null=True, verbose_name='summary')),
                ('platform', models.CharField(blank=True, choices=[('tw', 'Twitter'), ('fb', 'Facebook'), ('web', 'Website'), ('wa', 'WhatsApp'), ('yt', 'Youtube'), ('ig', 'Instagram'), ('other', 'Other')], max_length=6, null=True, verbose_name='platform')),
                ('current_status', models.CharField(blank=True, choices=[('open', 'Open'), ('closed', 'Closed'), ('abstenia', 'In abstentia subject to appeal or objection'), ('na', 'Not applicable')], max_length=8, null=True, verbose_name='status')),
                ('station_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Police station name')),
                ('detained', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('n/a', 'Not applicable')], max_length=6, null=True, verbose_name='detained?')),
                ('detained_for', models.IntegerField(blank=True, null=True, verbose_name='detained for number of days')),
                ('pledge_signing', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('refuse', 'Refused signing'), ('n/a', 'Not applicable')], max_length=6, null=True, verbose_name='Requested to sign pledge?')),
                ('reconciliation', models.NullBooleanField(verbose_name='reconciliation')),
                ('charge', models.TextField(blank=True, null=True, verbose_name='charge')),
                ('bail', models.IntegerField(blank=True, help_text='The amount in local currency', null=True, verbose_name='bail amount')),
                ('sentenced', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('postponed', 'Postponed'), ('inprocess', 'In the process'), ('n/a', 'Not applicable')], max_length=9, null=True, verbose_name='sentenced?')),
                ('content_deletion', models.CharField(blank=True, choices=[('forced', 'Forced to delete'), ('required', 'Required to delete'), ('No', 'No'), ('n/a', 'Not applicable')], max_length=10, null=True, verbose_name='Requested to delete content?')),
                ('sentence', models.TextField(blank=True, null=True, verbose_name='sentence')),
                ('in_absentia', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('n/a', 'Not applicable')], max_length=6, null=True, verbose_name='in absentia?')),
                ('contacted_via', models.CharField(blank=True, choices=[('phone', 'Phone call'), ('inperson', 'In person'), ('fax', 'Fax'), ('No', 'No')], max_length=10, null=True, verbose_name='Contacted via')),
                ('date_of_publication', models.DateField(blank=True, null=True, verbose_name='date of publication')),
                ('date_of_contact', models.DateField(blank=True, null=True, verbose_name='date of contact by cybercrime bureau')),
                ('date_of_investigation', models.DateField(blank=True, null=True, verbose_name='date of investigation')),
                ('date_of_detention', models.DateField(blank=True, null=True, verbose_name='date of detention')),
                ('duration_of_detention', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='duration of detention (in days)')),
                ('date_of_hearing', models.DateField(blank=True, null=True, verbose_name='date of hearing')),
                ('date_of_hearing_2', models.DateField(blank=True, null=True, verbose_name='date of second hearing')),
                ('date_of_release', models.DateField(blank=True, null=True, verbose_name='date of release')),
                ('date_of_ruling', models.DateField(blank=True, null=True, verbose_name='date of ruling')),
            ],
            options={
                'verbose_name': 'case',
                'verbose_name_plural': 'cases',
            },
        ),
        migrations.CreateModel(
            name='Defendant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40, verbose_name='first name')),
                ('first_name_ar', models.CharField(max_length=40, null=True, verbose_name='first name')),
                ('first_name_en', models.CharField(max_length=40, null=True, verbose_name='first name')),
                ('last_name', models.CharField(max_length=40, verbose_name='last name')),
                ('last_name_ar', models.CharField(max_length=40, null=True, verbose_name='last name')),
                ('last_name_en', models.CharField(max_length=40, null=True, verbose_name='last name')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=6, verbose_name='gender')),
                ('age_range', models.CharField(choices=[('<18', '<18'), ('18-30', '18-30'), ('31-45', '31-45'), ('46-60', '46-60'), ('>60', 'over 60')], max_length=6, verbose_name='age range')),
                ('citizenship', models.CharField(choices=[('lebanon', 'Lebanese'), ('syria', 'Syrian'), ('stateless', 'Stateless'), ('other', 'Other')], max_length=10, verbose_name='citizenship')),
                ('profession', models.CharField(blank=True, max_length=100, null=True, verbose_name='profession')),
                ('profession_ar', models.CharField(blank=True, max_length=100, null=True, verbose_name='profession')),
                ('profession_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='profession')),
            ],
            options={
                'verbose_name': 'defendant',
                'verbose_name_plural': 'defendants',
            },
        ),
        migrations.CreateModel(
            name='Judge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40, verbose_name='first name')),
                ('first_name_ar', models.CharField(max_length=40, null=True, verbose_name='first name')),
                ('first_name_en', models.CharField(max_length=40, null=True, verbose_name='first name')),
                ('last_name', models.CharField(max_length=40, verbose_name='last name')),
                ('last_name_ar', models.CharField(max_length=40, null=True, verbose_name='last name')),
                ('last_name_en', models.CharField(max_length=40, null=True, verbose_name='last name')),
                ('legal_entity', models.CharField(choices=[('army intel', 'Army Intelligence Branch')], max_length=10, verbose_name='legal entity')),
                ('kaza', models.CharField(blank=True, choices=[('Akkar', 'Akkar'), ('Minieh-Danieh', 'Minieh-Danieh'), ('Baalbeck', 'Baalbeck'), ('Hermel', 'Hermel'), ('Beirut', 'Beirut'), ('Rachiaya', 'Rachiaya'), ('West Bekaa', 'West Bekaa'), ('Zahleh', 'Zahleh'), ('Aley', 'Aley'), ('Baabda', 'Baabda'), ('Batroun', 'Batroun'), ('Chouf', 'Chouf'), ('El Metn', 'El Metn'), ('Jezzine', 'Jezzine'), ('Jubail', 'Jubail'), ('Kasrouane', 'Kasrouane'), ('Bint Jbayl', 'Bint Jbayl'), ('Hasbaya', 'Hasbaya'), ('Marjaayoun', 'Marjaayoun'), ('Nabatiyeh', 'Nabatiyeh'), ('Batroun', 'Batroun'), ('Bcharre', 'Bcharre'), ('Koura', 'Koura'), ('Minieh-Danieh', 'Minieh-Danieh'), ('Tripoli', 'Tripoli'), ('Zgharta', 'Zgharta'), ('Jezzine', 'Jezzine'), ('Nabatiyeh', 'Nabatiyeh'), ('Saida', 'Saida'), ('Sour', 'Sour')], max_length=20, null=True, verbose_name='kaza')),
            ],
            options={
                'verbose_name': 'judge',
                'verbose_name_plural': 'judge',
            },
        ),
        migrations.CreateModel(
            name='LawArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('law', models.CharField(choices=[('publication', 'Publications law'), ('penal', 'Penal code'), ('electronic', 'Electronic affairs'), ('military', 'Military law'), ('other', 'Other')], max_length=20, null=True, verbose_name='law')),
                ('number', models.CharField(max_length=100, verbose_name='number')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('name_ar', models.CharField(max_length=100, null=True, verbose_name='name')),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name='name')),
                ('url', models.URLField(blank=True, help_text='URL to the law text on the Lebanese University Centre for Law', null=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'law article',
                'verbose_name_plural': 'law articles',
            },
        ),
        migrations.CreateModel(
            name='Plaintiff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40, verbose_name='first name')),
                ('first_name_ar', models.CharField(max_length=40, null=True, verbose_name='first name')),
                ('first_name_en', models.CharField(max_length=40, null=True, verbose_name='first name')),
                ('last_name', models.CharField(max_length=40, verbose_name='last name')),
                ('last_name_ar', models.CharField(max_length=40, null=True, verbose_name='last name')),
                ('last_name_en', models.CharField(max_length=40, null=True, verbose_name='last name')),
            ],
            options={
                'verbose_name': 'plaintiff',
                'verbose_name_plural': 'plaintiffs',
            },
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('title_ar', models.CharField(max_length=100, null=True, verbose_name='title')),
                ('title_en', models.CharField(max_length=100, null=True, verbose_name='title')),
                ('url', models.URLField(verbose_name='URL')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.Case')),
            ],
            options={
                'verbose_name': 'Reference',
                'verbose_name_plural': 'References',
            },
        ),
        migrations.AddField(
            model_name='case',
            name='charged_using',
            field=models.ManyToManyField(blank=True, to='cases.LawArticle', verbose_name='charged using law article'),
        ),
        migrations.AddField(
            model_name='case',
            name='defendants',
            field=models.ManyToManyField(blank=True, to='cases.Defendant', verbose_name='defendants'),
        ),
        migrations.AddField(
            model_name='case',
            name='judge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cases.Judge', verbose_name='judge and court'),
        ),
        migrations.AddField(
            model_name='case',
            name='plaintiffs',
            field=models.ManyToManyField(blank=True, to='cases.Plaintiff', verbose_name='plaintiffs'),
        ),
    ]
