# Generated by Django 3.0.6 on 2020-06-11 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='charge_ar',
            field=models.TextField(blank=True, null=True, verbose_name='charge'),
        ),
        migrations.AddField(
            model_name='case',
            name='charge_en',
            field=models.TextField(blank=True, null=True, verbose_name='charge'),
        ),
        migrations.AddField(
            model_name='case',
            name='sentence_ar',
            field=models.TextField(blank=True, null=True, verbose_name='sentence'),
        ),
        migrations.AddField(
            model_name='case',
            name='sentence_en',
            field=models.TextField(blank=True, null=True, verbose_name='sentence'),
        ),
        migrations.AddField(
            model_name='case',
            name='station_name_ar',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Police station name'),
        ),
        migrations.AddField(
            model_name='case',
            name='station_name_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Police station name'),
        ),
    ]
