# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-10 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accused',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40, verbose_name='first name')),
                ('last_name', models.CharField(max_length=40, verbose_name='last name')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=6, verbose_name='gender')),
                ('citizenship', models.CharField(choices=[('leb', 'Lebanese'), ('syr', 'Syrian'), ('non', 'Stateless'), ('other', 'Not Lebanese')], max_length=6, verbose_name='citizenship')),
                ('profession', models.CharField(max_length=100, verbose_name='profession')),
                ('age_range', models.CharField(choices=[('<18', '<18'), ('18-30', '18-30'), ('31-45', '31-45'), ('46-60', '46-60'), ('>60', 'over 60')], max_length=6, verbose_name='age range')),
            ],
        ),
    ]
