# Generated by Django 3.0.6 on 2020-06-29 15:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_auto_20200611_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='case',
            name='last_modified',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Last modified'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='case',
            name='published',
            field=models.BooleanField(default=False, verbose_name='Published?'),
        ),
        migrations.AlterField(
            model_name='case',
            name='current_status',
            field=models.CharField(blank=True, choices=[('open', 'Open'), ('closed', 'Closed'), ('pending', 'Pending appeal or objection')], max_length=8, null=True, verbose_name='status'),
        ),
    ]
