# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-11 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_auto_20200210_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date'),
        ),
        migrations.AddField(
            model_name='case',
            name='people',
            field=models.ManyToManyField(to='cases.Accused', verbose_name='people'),
        ),
        migrations.AddField(
            model_name='case',
            name='platform',
            field=models.CharField(blank=True, choices=[('tw', 'Twitter'), ('fb', 'Facebook'), ('web', 'Website'), ('wa', 'WhatsApp'), ('yt', 'Youtube'), ('ig', 'Instagram'), ('other', 'Other')], max_length=6, null=True, verbose_name='platform'),
        ),
        migrations.AlterField(
            model_name='accused',
            name='profession',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='profession'),
        ),
        migrations.AlterField(
            model_name='case',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='case',
            name='name_ar',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='case',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(blank=True, choices=[('open', 'Open'), ('closed', 'Closed'), ('abstenia', 'In abstentia subject to appeal or objection'), ('na', 'Not applicable')], max_length=6, null=True, verbose_name='status'),
        ),
    ]
