# Generated by Django 3.0.6 on 2020-07-03 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_auto_20200629_1806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='judge',
        ),
        migrations.AddField(
            model_name='case',
            name='judges',
            field=models.ManyToManyField(blank=True, to='cases.Judge', verbose_name='judges and their court'),
        ),
    ]
