# Generated by Django 3.0.6 on 2020-07-24 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_auto_20200703_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='country',
            field=models.CharField(choices=[('lebanon', 'Lebanon'), ('jordan', 'Jordan'), ('other', 'Other')], default='lebanon', max_length=10, verbose_name='country'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='case',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Last modified'),
        ),
    ]
