# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-11 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_auto_20200211_1519'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plaintiff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40, verbose_name='first name')),
                ('first_name_en', models.CharField(max_length=40, null=True, verbose_name='first name')),
                ('first_name_ar', models.CharField(max_length=40, null=True, verbose_name='first name')),
                ('last_name', models.CharField(max_length=40, verbose_name='last name')),
                ('last_name_en', models.CharField(max_length=40, null=True, verbose_name='last name')),
                ('last_name_ar', models.CharField(max_length=40, null=True, verbose_name='last name')),
            ],
        ),
        migrations.RenameModel(
            old_name='Accused',
            new_name='Defendant',
        ),
        migrations.RemoveField(
            model_name='case',
            name='people',
        ),
        migrations.AddField(
            model_name='case',
            name='defendants',
            field=models.ManyToManyField(to='cases.Defendant', verbose_name='defendants'),
        ),
        migrations.AddField(
            model_name='case',
            name='plaintiffs',
            field=models.ManyToManyField(to='cases.Plaintiff', verbose_name='plaintiffs'),
        ),
    ]
