# Generated by Django 3.0.7 on 2020-09-15 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_auto_20200724_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='plaintiff',
            name='description',
            field=models.CharField(default='', max_length=200, verbose_name='description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='case',
            name='current_status',
            field=models.CharField(blank=True, choices=[('open', 'Open'), ('closed', 'Closed'), ('pending', 'Pending appeal or objection'), ('unknown', 'Unknown')], max_length=8, null=True, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='defendant',
            name='citizenship',
            field=models.CharField(choices=[('lebanon', 'Lebanese'), ('syria', 'Syrian'), ('palestine', 'Palestine'), ('stateless', 'Stateless'), ('unknown', 'Unknown'), ('other', 'Other')], max_length=10, verbose_name='citizenship'),
        ),
    ]
