# Generated by Django 3.0.7 on 2020-09-16 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0006_auto_20200916_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='plaintiff',
            name='description_ar',
            field=models.CharField(max_length=200, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='plaintiff',
            name='description_en',
            field=models.CharField(max_length=200, null=True, verbose_name='description'),
        ),
    ]
