# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-11 16:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0006_auto_20200211_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='name',
        ),
        migrations.RemoveField(
            model_name='case',
            name='name_ar',
        ),
        migrations.RemoveField(
            model_name='case',
            name='name_en',
        ),
    ]
