# Generated by Django 3.0.7 on 2020-09-16 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0007_auto_20200916_0411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='judge',
            name='legal_entity',
            field=models.CharField(choices=[('publications', 'Publications court'), ('cassation', 'Cassation court'), ('appeals', 'Appellant court'), ('criminal', 'Criminal court'), ('military police', 'Military police centre'), ('army intel', 'Army Intelligence Branch'), ('military court', 'Military court'), ('state security', 'State security apparatus'), ('justice palace', 'Palace of Justice'), ('criminal investigations', 'Central bureau of criminal investigations'), ('public prosecutor', 'Executive public prosecutor'), ('general security', 'General security')], max_length=25, verbose_name='legal entity'),
        ),
    ]
