# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-11 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0008_auto_20200211_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='name_ar',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='case',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='case',
            name='summary_ar',
            field=models.TextField(blank=True, null=True, verbose_name='summary'),
        ),
        migrations.AddField(
            model_name='case',
            name='summary_en',
            field=models.TextField(blank=True, null=True, verbose_name='summary'),
        ),
    ]
