# Generated by Django 3.0.7 on 2020-10-06 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0009_auto_20201006_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='defendant',
            name='description_ar',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='defendant',
            name='description_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='description'),
        ),
    ]
