# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-11 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0009_auto_20200211_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='defendant',
            name='profession_ar',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='profession'),
        ),
        migrations.AddField(
            model_name='defendant',
            name='profession_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='profession'),
        ),
    ]
