# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-20 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0011_auto_20200218_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='name',
        ),
        migrations.RemoveField(
            model_name='case',
            name='name_ar',
        ),
        migrations.RemoveField(
            model_name='case',
            name='name_en',
        ),
        migrations.AddField(
            model_name='case',
            name='country',
            field=models.CharField(choices=[('tw', 'Twitter'), ('fb', 'Facebook'), ('web', 'Website'), ('wa', 'WhatsApp'), ('yt', 'Youtube'), ('ig', 'Instagram'), ('other', 'Other')], default='lb', max_length=100, verbose_name='country'),
            preserve_default=False,
        ),
    ]
