# Generated by Django 3.0.7 on 2020-11-10 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0012_auto_20201106_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='judge',
            name='legal_entity',
            field=models.CharField(choices=[('Lebanon', (('publications', 'Publications court'), ('cassation', 'Cassation court'), ('appeals', 'Appellant court'), ('criminal', 'Criminal court'), ('military police', 'Military police centre'), ('army intel', 'Army Intelligence Branch'), ('military court', 'Military court'), ('state security', 'State security apparatus'), ('justice palace', 'Palace of Justice'), ('criminal investigations', 'Central bureau of criminal investigations'), ('public prosecutor', 'Executive public prosecutor'), ('general security', 'General security'))), ('Jordan', (('jo_reconciliation', 'Reconciliation court'), ('jo_initial', 'Initial court'), ('jo_appeals', 'Appeals court'), ('jo_cessation', 'Cessation court'), ('jo_administrative', 'Administrative court'), ('jo_constitutional', 'Constitutional court'), ('jo_grand_criminal', 'Grand criminal court'), ('jo_state security', 'State security court')))], max_length=25, verbose_name='legal entity'),
        ),
    ]
