# Generated by Django 3.0.7 on 2020-11-15 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0013_auto_20201110_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='judge',
            name='legal_entity',
            field=models.CharField(choices=[('Lebanon', (('publications', 'Publications court'), ('cassation', 'Cassation court'), ('appeals', 'Appellant court'), ('criminal', 'Criminal court'), ('military police', 'Military police centre'), ('army intel', 'Army Intelligence Branch'), ('military court', 'Military court'), ('state security', 'State security apparatus'), ('justice palace', 'Palace of Justice'), ('criminal investigations', 'Central bureau of criminal investigations'), ('public prosecutor', 'Executive public prosecutor'), ('general security', 'General security'))), ('Jordan', (('jo magistrate', 'Magistrate’s Courts'), ('jo first instance', 'Courts of First Instance'), ('jo appeal', 'Courts of Appeal'), ('jo cessation', 'Courts of Cassation'), ('jo administrative', 'Administrative court'), ('jo constitutional', 'Constitutional court'), ('jo major felonies', 'Major Felonies Court'), ('jo state security', 'State Security Court')))], max_length=25, verbose_name='legal entity'),
        ),
        migrations.AlterField(
            model_name='lawarticle',
            name='law',
            field=models.CharField(choices=[('Lebanon', (('publication', 'Publications law'), ('penal', 'Penal code'), ('electronic', 'Electronic affairs'), ('military', 'Military law'), ('other', 'Other'))), ('Jordan', (('jo anti-terrorism', 'Anti-terrorism law'), ('jo telecom', 'Telecommunications law'), ('jo cybercrimes', 'Cybercrimes law'), ('jo penal', 'Jordanian penal code'), ('jo press', 'Press and publications law'), ('jo other', 'Other')))], max_length=20, null=True, verbose_name='law'),
        ),
    ]
