# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-20 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0017_auto_20200220_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='date_of_contact',
            field=models.DateField(blank=True, null=True, verbose_name='date of contact by cybercrime bureau'),
        ),
        migrations.AddField(
            model_name='case',
            name='date_of_detention',
            field=models.DateField(blank=True, null=True, verbose_name='date of detention'),
        ),
        migrations.AddField(
            model_name='case',
            name='date_of_hearing',
            field=models.DateField(blank=True, null=True, verbose_name='date of hearing'),
        ),
        migrations.AddField(
            model_name='case',
            name='date_of_hearing_2',
            field=models.DateField(blank=True, null=True, verbose_name='date of second hearing'),
        ),
        migrations.AddField(
            model_name='case',
            name='date_of_investigation',
            field=models.DateField(blank=True, null=True, verbose_name='date of investigation'),
        ),
        migrations.AddField(
            model_name='case',
            name='date_of_post',
            field=models.DateField(blank=True, null=True, verbose_name='date of publication of expression'),
        ),
        migrations.AddField(
            model_name='case',
            name='date_of_release',
            field=models.DateField(blank=True, null=True, verbose_name='date of release'),
        ),
        migrations.AddField(
            model_name='case',
            name='date_of_ruling',
            field=models.DateField(blank=True, null=True, verbose_name='date of ruling'),
        ),
        migrations.AddField(
            model_name='case',
            name='duration_of_detention',
            field=models.IntegerField(blank=True, null=True, verbose_name='duration of detention (in days)'),
        ),
    ]
