# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-20 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0018_auto_20200220_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='duration_of_detention',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='duration of detention (in days)'),
        ),
    ]
