# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-20 16:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0019_auto_20200220_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='Judge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40, verbose_name='first name')),
                ('last_name', models.CharField(max_length=40, verbose_name='last name')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=6, verbose_name='gender')),
                ('legal_entity', models.CharField(choices=[('army intel', 'Army Intelligence Branch')], max_length=6, verbose_name='legal entity')),
                ('kaza', models.CharField(blank=True, choices=[('Akkar', 'Akkar'), ('Minieh-Danieh', 'Minieh-Danieh'), ('Baalbeck', 'Baalbeck'), ('Hermel', 'Hermel'), ('Beirut', 'Beirut'), ('Rachiaya', 'Rachiaya'), ('West Bekaa', 'West Bekaa'), ('Zahleh', 'Zahleh'), ('Aley', 'Aley'), ('Baabda', 'Baabda'), ('Batroun', 'Batroun'), ('Chouf', 'Chouf'), ('El Metn', 'El Metn'), ('Jezzine', 'Jezzine'), ('Jubail', 'Jubail'), ('Kasrouane', 'Kasrouane'), ('Bint Jbayl', 'Bint Jbayl'), ('Hasbaya', 'Hasbaya'), ('Marjaayoun', 'Marjaayoun'), ('Nabatiyeh', 'Nabatiyeh'), ('Batroun', 'Batroun'), ('Bcharre', 'Bcharre'), ('Koura', 'Koura'), ('Minieh-Danieh', 'Minieh-Danieh'), ('Tripoli', 'Tripoli'), ('Zgharta', 'Zgharta'), ('Jezzine', 'Jezzine'), ('Nabatiyeh', 'Nabatiyeh'), ('Saida', 'Saida'), ('Sour', 'Sour')], max_length=20, null=True, verbose_name='kaza')),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='judge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cases.Judge', verbose_name='judge and court'),
        ),
    ]
