# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-12 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0021_auto_20200220_1656'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='case',
            options={'verbose_name': 'case', 'verbose_name_plural': 'cases'},
        ),
        migrations.AlterModelOptions(
            name='defendant',
            options={'verbose_name': 'defendant', 'verbose_name_plural': 'defendants'},
        ),
        migrations.AlterModelOptions(
            name='judge',
            options={'verbose_name': 'judge', 'verbose_name_plural': 'judge'},
        ),
        migrations.AlterModelOptions(
            name='lawarticle',
            options={'verbose_name': 'law article', 'verbose_name_plural': 'law articles'},
        ),
        migrations.AlterModelOptions(
            name='plaintiff',
            options={'verbose_name': 'plaintiff', 'verbose_name_plural': 'plaintiffs'},
        ),
        migrations.RemoveField(
            model_name='case',
            name='date',
        ),
        migrations.RemoveField(
            model_name='case',
            name='date_of_post',
        ),
        migrations.AddField(
            model_name='case',
            name='date_of_publication',
            field=models.DateField(blank=True, null=True, verbose_name='date of publication'),
        ),
        migrations.AddField(
            model_name='case',
            name='reconciliation',
            field=models.NullBooleanField(verbose_name='reconciliation'),
        ),
        migrations.AddField(
            model_name='case',
            name='station_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Police station name'),
        ),
        migrations.AddField(
            model_name='lawarticle',
            name='url',
            field=models.URLField(blank=True, help_text='URL to the law text on the Lebanese University Centre for Law', null=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='case',
            name='content_deletion',
            field=models.CharField(blank=True, choices=[('forced', 'Forced to delete'), ('required', 'Required to delete'), ('No', 'No'), ('n/a', 'Not applicable')], max_length=10, null=True, verbose_name='Requested to delete content?'),
        ),
        migrations.AlterField(
            model_name='case',
            name='country',
            field=models.CharField(choices=[('lebanon', 'Lebanon'), ('jordan', 'Jordan'), ('other', 'Other')], max_length=10, verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='case',
            name='pledge_signing',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('refuse', 'Refused signing'), ('n/a', 'Not applicable')], max_length=6, null=True, verbose_name='Requested to sign pledge?'),
        ),
        migrations.AlterField(
            model_name='defendant',
            name='citizenship',
            field=models.CharField(choices=[('lebanon', 'Lebanese'), ('syria', 'Syrian'), ('stateless', 'Stateless'), ('other', 'Other')], max_length=10, verbose_name='citizenship'),
        ),
    ]
