# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-16 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0023_auto_20200313_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawarticle',
            name='law',
            field=models.CharField(choices=[('publication', 'Publications law'), ('penal', 'Penal code'), ('electronic', 'Electronic affairs'), ('military', 'Military law'), ('other', 'Other')], max_length=20, null=True, verbose_name='law'),
        ),
    ]
