# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-16 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0024_auto_20200316_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='bail',
            field=models.IntegerField(blank=True, help_text='The amount in local currency', null=True, verbose_name='bail amount'),
        ),
    ]
